### ISSUE TITLE
Doesn't load on 2nd dashboard, unless page is refreshed

### ISSUE THREAD

**Issue by Meelobee** [Villhellm/lovelace-animated-background#14]
Hey Villhellm, 
Thanks for the great addition to Home Assistant. I have a question about how it loads on different dashboards. 

In my HA setup I have 2 Dashboards and I would like to add the animated backgrounds on the second dashboard only. Each dashboard uses its own Lovelace config file and I've added the config below to the 2nd dashboard only.

```
animated_background:
  views:
    - config:
        default_url: /local/backgrounds-animated/sunny.html
        entity: sun.sun
        state_url:
          above_horizon: /local/backgrounds-animated/sunny.html
          below_horizon: /local/backgrounds-animated/night.html
      path: /lovelace-rineke/temperatuur
    - config:
        default_url: /local/backgrounds-animated/sunny.html
        entity: sun.sun
        state_url:
          above_horizon: /local/backgrounds-animated/sunny.html
          below_horizon: /local/backgrounds-animated/night.html
      path: /lovelace-rineke/weer
```
But when I view the second dashboard, it opens  with it's static background (in my case a custom image) The animated background only shows after I manually refesh the page. 
Is there any way to avoid that and have the animated background show right away when opening the second dashboard?

Home Assistant version: 0.108.9
Animated Background version: dd7563b
Browser: Chrome (81.0.4044.129)

Thanks for your time :)
