### ISSUE TITLE
no longer shows backgrounds

### ISSUE THREAD

**Issue by garywilson4** [Villhellm/lovelace-animated-background#15]
since updating to "d0699ca" home assistant 0.109.2 the backgrounds no longer load 
if i set my background opacity to a low number the backgrounds show but the configuration pages and development pages are awful.
it worked fine pre this update 
```
animated_background:
  default_url: /hacsfiles/lovelace-animated-background/background-animations/sunny.html
  entity: weather.forecast
  state_url:
    clear-night: /hacsfiles/lovelace-animated-background/background-animations/night.html
    cloudy: /hacsfiles/lovelace-animated-background/background-animations/cloudy.html
    fog: /hacsfiles/lovelace-animated-background/background-animations/fog.html
    mostlycloudy: >-
      /hacsfiles/lovelace-animated-background/background-animations/mostlycloudy.html
    partlycloudy: /hacsfiles/lovelace-animated-background/background-animations/cloudy.html
    sunny: /hacsfiles/lovelace-animated-background/background-animations/sunny.html
```
![Screenshot_1](https://user-images.githubusercontent.com/36335413/80849751-895a8e00-8c10-11ea-8187-0c8fe20c5dc3.jpg)
