### ISSUE TITLE
White background (instead of the theme one) when no animated_backround is configured

### ISSUE THREAD

**Issue by SeLLeRoNe** [Villhellm/lovelace-animated-background#16]
**Your Animated Background configuration**

I only have this in ui-lovelace.yaml , not in the additional dashboards (management and test ones)

```
animated_background:
  default_url: /local/animated_backgrounds/sunny.html
  included_users:
    - Andrea Iannucci
  included_devices:
    - windows
  entity: "weather.dark_sky"
  state_url:
    'sunny': /local/animated_backgrounds/sunny.html
    'partlycloudy': /local/animated_backgrounds/cloudy.html
    'cloudy': /local/animated_backgrounds/cloudy.html
    'mostlycloudy': /local/animated_backgrounds/mostlycloudy.html
    'clear-night': /local/animated_backgrounds/night.html
    'fog': /local/animated_backgrounds/fog.html

```

**Version of Home Assistant**
"Latest" is not a version number. Please provide the actual version number.
1.109.2

**Describe the bug**
All the dashboards are loading a white background instead of the theme background presumably because the animated background is not configured for those dashboards.

**Browser console log**
Post anything related to animated-background.js
Not apparent/clear related error in the dashboard

**To Reproduce**
1. Create a new dashboard
2. Don't configure any animated_background
3. View the dashboard

**Expected behavior**
Use the default theme background if no configuration is present.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 81.0.4044.129

**Smartphone (please complete the following information):**

**Screenshots**
![image](https://user-images.githubusercontent.com/9599441/80871346-4bab4300-8cac-11ea-8492-e7f79f4eef8f.png)

**Additional context**
