### ISSUE TITLE
Animated background applied on non-included devices.

### ISSUE THREAD

**Issue by SeLLeRoNe** [Villhellm/lovelace-animated-background#17]
**Your Animated Background configuration**

```
animated_background:
  default_url: /local/animated_backgrounds/sunny.html
  included_users:
    - Andrea Iannucci
  included_devices:
    - windows
  entity: "weather.dark_sky"
  state_url:
    'sunny': /local/animated_backgrounds/sunny.html
    'partlycloudy': /local/animated_backgrounds/cloudy.html
    'cloudy': /local/animated_backgrounds/cloudy.html
    'mostlycloudy': /local/animated_backgrounds/mostlycloudy.html
    'clear-night': /local/animated_backgrounds/night.html
    'fog': /local/animated_backgrounds/fog.html

```

**Version of Home Assistant** 0.109.2
"Latest" is not a version number. Please provide the actual version number.

**Describe the bug**
Even configuring only "windows" as allowed device, I can see a white background (not the theme background) on the HA Mobile App and using Chrome

**Browser console log**
Post anything related to animated-background.js

**To Reproduce**
1. Configure only "windows" as allowd device
2. Open the UI using a mobile phone browser or HA Companion App

**Expected behavior**
Not showing a white background but the theme one

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: OnePlus 5
 - OS: OxygenOS 9.0.11 based on Android 9
 - Browser: Chrome 
- Version: 81.0.4044.117
 - App: Home Companion App 1.8.0-159 and Chrome 81.0.4044.117
 - Version: 1.8.0-159

**Screenshots**
![image](https://user-images.githubusercontent.com/9599441/80871511-51555880-8cad-11ea-9bca-e2efa521d2f1.png)

**Additional context**
