### ISSUE TITLE
Video doesn't show when in panel mode

### ISSUE THREAD

**Issue by matt8707** [Villhellm/lovelace-animated-background#18]
**Your Animated Background configuration**

```
animated_background:
  default_url: /hacsfiles/lovelace-animated-background/background-animations/sunny.html
views:
  - cards:
      - type: entities
        style: 'ha-card {background: none;}'
        entities:
          - remote.sovrum
    path: default_view
    panel: true
    title: Home
```

**Version of Home Assistant**
0.109.2

**Describe the bug**
Video doesn't show when in panel mode

**Browser console log**
Animated Background: Starting
Animated Background: Applying default background

**Additional context**
Even if the cards background is set to none
