### ISSUE TITLE
Per user filter stopped working

### ISSUE THREAD

**Issue by SeLLeRoNe** [Villhellm/lovelace-animated-background#20]
**Your Animated Background configuration**

```
animated_background:
  default_url: /local/animated_backgrounds/sunny.html
  included_users:
    - Andrea Iannucci
  included_devices:
    - windows
  entity: "weather.dark_sky"
  state_url:
    'sunny': /local/animated_backgrounds/sunny.html
    'partlycloudy': /local/animated_backgrounds/cloudy.html
    'cloudy': /local/animated_backgrounds/cloudy.html
    'mostlycloudy': /local/animated_backgrounds/mostlycloudy.html
    'clear-night': /local/animated_backgrounds/night.html
    'fog': /local/animated_backgrounds/fog.html

```

**Version of Home Assistant** : 0.109.3
"Latest" is not a version number. Please provide the actual version number.

**Describe the bug**
The "inlcude_user" filter I believe stopped working from last release

**Browser console log**
Post anything related to animated-background.js

```
animated-background.js:193 Uncaught TypeError: Cannot read property 'user' of null
    at enabled (animated-background.js:193)
    at animated-background.js:244
enabled @ animated-background.js:193
(anonymous) @ animated-background.js:244
```

**To Reproduce**
1. Filter Animated Background to be used by a specific user only (haven't tried the exclude part)
2. Open Lovelace

**Expected behavior**
The specified user should be the only able to see the animate background

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 81.0.4044.129

**Smartphone (please complete the following information):**

**Screenshots**

**Additional context**
