### ISSUE TITLE
Animated Background doesn't get "disabled" on view change

### ISSUE THREAD

**Issue by SeLLeRoNe** [Villhellm/lovelace-animated-background#22]
**Your Animated Background configuration**

Dashboard config
```
---
# This is actually just a bootstrap for my Lovelace configuration.
# It loads all resources for Lovelace dynamically from subfolders
# inside the `lovelace/resources` directory.
#
# Views are actually include one by one, this to guarentee the order of
# the tabs of the view in the UI.
#
title: Test
preload_cards:
  - markdown
preload_rows:
  - divider
custom_header:
  compact_mode: true
  footer_mode: false
  hide_header: false
  header_text: '{{ time }}' # See templates section for more on this.
  hide_config: true
  hide_raw: true
  hide_unused: true
  hide_help: true
  # Add the below to theme the header
  background: var(--app-header-background-color)
  elements_color: var(--app-header-text-color)
  active_tab_color: var(--state-icon-active-color)
  tab_indicator_color: var(--state-icon-active-color)
animated_background: !include lovelace/animated_backgrounds/test.yaml
decluttering_templates: !include_dir_merge_named lovelace/templates/
views:
  - !include lovelace/views/test.yaml
  - !include lovelace/views/test_map.yaml
  - !include lovelace/views/surveillance.yaml
```

test.yaml 
```
---
debug: true
included_users:
  - Andrea Iannucci
included_devices:
  - windows
groups:
  - name: test
    config:
      entity: "weather.dark_sky"
      state_url:
        'partlycloudy': /local/animated_backgrounds/test.html

```

**Version of Home Assistant**
"Latest" is not a version number. Please provide the actual version number.
0.109.3
**Describe the bug**

**Browser console log**
Post anything related to animated-background.js
First load
```
Animated Background DEBUG: Configured entity weather.dark_sky is now partlycloudy
animated-background.js:28 Animated Background DEBUG: Starting
animated-background.js:35 Animated Background DEBUG: Debug mode enabled
animated-background.js:37 {auth: u, connection: l, connected: true, states: {…}, config: {…}, …}
animated-background.js:35 Animated Background DEBUG: Panel mode detected
animated-background.js:35 Animated Background DEBUG: Removing view background
animated-background.js:37 {entity: "weather.dark_sky", state_url: {…}}
```
Update without cache:
```
 
animated-background.js:24 Animated Background: Starting
animated-background.js:35 Animated Background DEBUG: Debug mode enabled
animated-background.js:37 {auth: u, connection: l, connected: true, states: {…}, config: {…}, …}
animated-background.js:28 Animated Background DEBUG: Configured entity weather.dark_sky is now partlycloudy
```

Change view (in the same dashboard), this view have no animated_background configured.
```
Animated Background DEBUG: View switched, no configuration found
```

**To Reproduce**

**Expected behavior**
The theme default background should be restored upon view change, if the view doesn't have animated_background configuration.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 81.0.4044.129

**Smartphone (please complete the following information):**

**Screenshots**

First fresh load (no cache):
![image](https://user-images.githubusercontent.com/9599441/81004768-2f92d780-8e4d-11ea-938c-f18bbce33530.png)

View change:
![image](https://user-images.githubusercontent.com/9599441/81004788-37527c00-8e4d-11ea-995a-61e5a7e13a43.png)

View reload:
![image](https://user-images.githubusercontent.com/9599441/81004818-420d1100-8e4d-11ea-83f4-c05372cc46b1.png)

Back to first view (with animated_background)
![image](https://user-images.githubusercontent.com/9599441/81004845-4df8d300-8e4d-11ea-9d49-1129af6c8050.png)

**Additional context**
