### ISSUE TITLE
Config not found and no animated background loaded

### ISSUE THREAD

**Issue by SeLLeRoNe** [Villhellm/lovelace-animated-background#23]
**Your Animated Background configuration**

```
---
# This is actually just a bootstrap for my Lovelace configuration.
# It loads all resources for Lovelace dynamically from subfolders
# inside the `lovelace/resources` directory.
#
# Views are actually include one by one, this to guarentee the order of
# the tabs of the view in the UI.
#
title: Home Control Panel
preload_cards:
  - hui-element
  - markdown
  - conditional
preload_rows:
  - divider
custom_header:
  compact_mode: true
  footer_mode: false
  hide_header: false
  header_text: '{{ time }}' # See templates section for more on this.
  hide_config: true
  hide_raw: true
  hide_unused: true
  hide_help: true
#  button_icons:
#    menu: mdi:skull
#    voice: mdi:home
#    options: mdi:death-star-variant
#  hide_tabs:
#    - 5 to 9
#    - 0
#    - home
#  tab_icons:
#    0: mdi:skull
#    home: mdi:home
#    7: mdi:death-star-variant
  exceptions:
    - conditions:
        user: sonia
      config:
         hide_tabs:
           - 9 to 20
#        menu_dropdown: true
#    - conditions:
#        user: maykar, Bram Kragten, Ludeeus
#        user_agent: Mobile
#        media_query: "(max-width: 600px)"
#      config:
#        footer_mode: true
#        reverse_button_direction: true
#        reverse_tab_direction: true
#    - conditions:
#        query_string: kiosk
#      config:
#        kiosk_mode: true
  # Add the below to theme the header
  background: var(--app-header-background-color)
  elements_color: var(--app-header-text-color)
  active_tab_color: var(--state-icon-active-color)
  tab_indicator_color: var(--state-icon-active-color)
animated_background: !include lovelace/animated_backgrounds/default.yaml
decluttering_templates: !include_dir_merge_named lovelace/templates/
views:
  - !include lovelace/views/house.yaml
  - !include lovelace/views/living_room.yaml
  - !include lovelace/views/kitchen.yaml
  - !include lovelace/views/studio.yaml
  - !include lovelace/views/master_bedroom.yaml
  - !include lovelace/views/bedroom_luca.yaml
  - !include lovelace/views/bathroom.yaml
  - !include lovelace/views/laundry_room.yaml
  - !include lovelace/views/patio.yaml
  - !include lovelace/views/health.yaml
  - !include lovelace/views/weather.yaml

```
default.yaml
```
---
debug: true
included_devices:
  - windows
groups:
  - name: weather
    config:
      entity: "weather.dark_sky"
      state_url:
        'sunny': /local/animated_backgrounds/sunny.html
        'partlycloudy': /local/animated_backgrounds/cloudy.html
        'cloudy': /local/animated_backgrounds/cloudy.html
        'mostlycloudy': /local/animated_backgrounds/mostlycloudy.html
        'rainy': /local/animated_backgrounds/rainy.html
        'clear-night': /local/animated_backgrounds/night.html
        'fog': /local/animated_backgrounds/fog.html
```

**Version of Home Assistant**
"Latest" is not a version number. Please provide the actual version number.
0.109.3

**Describe the bug**
Animated background not loaded despite the config (somehow work on another dashboard, see other ticket)

**Browser console log**
Post anything related to animated-background.js
```
Animated Background: Starting
animated-background.js:35 Animated Background DEBUG: Debug mode enabled
animated-background.js:37 {auth: u, connection: l, connected: true, states: {…}, config: {…}, …}
animated-background.js:35 Animated Background DEBUG: Not loaded, this is the currently found configuration
```

**To Reproduce**

**Expected behavior**
Animated background to load :)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 81.0.4044.129

**Smartphone (please complete the following information):**

**Screenshots**
![image](https://user-images.githubusercontent.com/9599441/81005094-b0ea6a00-8e4d-11ea-9895-9c5a0157730b.png)

**Additional context**

**Comment by Villhellm** [comment]
Can you also post the view configurations that you're having trouble with?

**Comment by SeLLeRoNe** [comment]
Do you need the entire thing or just the first few lines?

**Comment by Villhellm** [comment]
Just the first few lines as long as it includes any `animated_background:` configuration

**Comment by SeLLeRoNe** [comment]
```
title: Home
icon: mdi:home
panel: true
animated_background: weather
cards:
  - type: custom:layout-card
    layout: vertical
    cards:
      - type: custom:stack-in-card
        mode: vertical
        cards:
          - type: custom:decluttering-card
            template: title
            variables:
```
