### ISSUE TITLE
default_url as list

### ISSUE THREAD

**Issue by SeLLeRoNe** [Villhellm/lovelace-animated-background#26]
**Describe the bug**
On a test view I don't want to define the background from the state of a specific entity but I would like to cycle from different backgrounds (mainly to test them).

**Your Animated Background configuration**

```yaml
groups:
  - name: test
    config:
      default_url:
        - "/local/animated_backgrounds/test/Androm_Spin.mp4"
        - "/local/animated_backgrounds/test/biostorm.mp4"
        - "/local/animated_backgrounds/test/biostorm2.mp4"
        - "/local/animated_backgrounds/test/Bubbles_Animation.mp4"
        - "/local/animated_backgrounds/test/light_burst_animation.mp4"
        - "/local/animated_backgrounds/test/scifi-spin-v4.mp4"
        - "/local/animated_backgrounds/test/scifitunnel03.mp4"
        - "/local/animated_backgrounds/test/scifitunnel03.mp4"
        - "/local/animated_backgrounds/test/spin_cycle.mp4"
```

**Your view configuration if it contains animated_background**

```yaml
animated_background:
  your_config
```

**Version Numbers**
"Latest" is not a version number

  - Home Assistant: 0.109.6
  - Animated Background: 0.5.0

**Browser console log**
Post anything related to animated-background.js

**To Reproduce**

**Expected behavior**
Havint the background to cycle from the default_url without having to be binded to a specific entity.

**Device (please complete the following information):**

**Screenshots**

**Comment by SeLLeRoNe** [comment]
I just realised that I used the bug report instead of the FR template, sorry!

**Comment by Villhellm** [comment]
Sorry, using an entity state is the way to test backgrounds. Cycling wouldn't really be possible because the array is only meant to function as a pool for random selection.

Here's an input select configuration and an animated background group to help

Input Select
```yaml
input_select:
  background_test:
    name: Background Test
    options:
      - Background 1
      - Background 2
      - Background 3
      - Background 4
      - Background 5
      - Background 6
      - Background 7
      - Background 8
      - Background 9
```

Animated Background group
```yaml
- name: background_test
  config:
    entity: input_select.background_test
    state_url:
      'Background 1' - "local/animated_backgrounds/test/Androm_Spin.mp4"
      'Background 2' - "local/animated_backgrounds/test/biostorm.mp4",
      'Background 3' - "local/animated_backgrounds/test/biostorm2.mp4"
      'Background 4' - "local/animated_backgrounds/test/Bubbles_Animation.mp4"
      'Background 5' - "local/animated_backgrounds/test/light_burst_animation.mp4"
      'Background 6' - "local/animated_backgrounds/test/scifi-spin-v4.mp4"
      'Background 7' - "local/animated_backgrounds/test/scifitunnel03.mp4"
      'Background 8' - "local/animated_backgrounds/test/scifitunnel03.mp4"
      'Background 9' - "local/animated_backgrounds/test/spin_cycle.mp4"
```
Admittedly I haven't tested these configs, but they should be valid.

PS make sure you don't try to use commas after each entry, the yaml parser will have a fit 😉 and no worries about the issue template, I understood what you were asking for.
