### ISSUE TITLE
Screen starts flickering on tablet and mobile (Both Samsung)

### ISSUE THREAD

**Issue by cpolhout** [Villhellm/lovelace-animated-background#35]
[20200810_170244_1 (1).mp4.zip](https://github.com/Villhellm/lovelace-animated-background/files/5051632/20200810_170244_1.1.mp4.zip)

**Describe the bug**
I have a tablet on the wall and installed animated background latest version. This works great, but sometimes, especially after waking up, the screen starts to flicker. It looks like it happens when the background is reloaded. I saw the same issue on my mobile phone.

On the tablet i'm running Fully Kiosk Browser

Without animated background i don't have this issue. On a mac with Chrome also not.

**Your Animated Background configuration**

```yaml
animated_background:
  debug: true
  default_url: /local/backgrounds/guwb10mfddctfvwioaex.hd.mp4
  enabled: true
  entity: weather.edison
  state_url:
    clear-night:
      - /local/backgrounds/x9dr8caygivq5secll7i.hd.mp4
      - /local/backgrounds/v26zyfd6yf0r33s46vpe.hd.mp4
      - /local/backgrounds/ypy8bw9fgw1zv2b4htp2.hd.mp4
      - /local/backgrounds/rosz2gi676xhkiw1ut6i.hd.mp4
    cloudy:
      - /local/backgrounds/13e0s6coh6ayapvdyqnv.hd.mp4
      - /local/backgrounds/aorl3skmssy7udwopk22.hd.mp4
      - /local/backgrounds/qed6wvf2igukiioykg3r.hd.mp4
      - /local/backgrounds/3rd72eezaj6d23ahlo7y.hd.mp4
      - /local/backgrounds/9m11gd43m6qn3y93ntzp.hd.mp4
      - /local/backgrounds/hrkw2m8eofib9sk7t1v2.hd.mp4
    fog:
      - /local/backgrounds/vwqzlk4turo2449be9uf.hd.mp4
      - /local/backgrounds/5363uhabodwwrzgnq6vx.hd.mp4
    mostlycloudy:
      - /local/backgrounds/e95h5cqyvhnrk4ytqt4q.hd.mp4
      - /local/backgrounds/l2bjw34wnusyf5q2qq3p.hd.mp4
      - /local/backgrounds/rrgta099ulami3zb9fd2.hd.mp4
    partlycloudy:
      - /local/backgrounds/13e0s6coh6ayapvdyqnv.hd.mp4
      - /local/backgrounds/aorl3skmssy7udwopk22.hd.mp4
      - /local/backgrounds/qed6wvf2igukiioykg3r.hd.mp4
      - /local/backgrounds/3rd72eezaj6d23ahlo7y.hd.mp4
      - /local/backgrounds/9m11gd43m6qn3y93ntzp.hd.mp4
      - /local/backgrounds/hrkw2m8eofib9sk7t1v2.hd.mp4
    rainy: /local/backgrounds/f0w23bd0enxur5ff0bxz.hd.mp4
    sunny:
      - /local/backgrounds/hlhff0h8md4ev0kju5be.hd.mp4
      - /local/backgrounds/zjqsoc6ecqhntpl5vacs.hd.mp4
      - /local/backgrounds/jvw1avupguhfbo11betq.hd.mp4
      - /local/backgrounds/8cmeusxf3pkanai43djs.hd.mp4
      - /local/backgrounds/guwb10mfddctfvwioaex.hd.mp4
```

**Your view configuration if it contains animated_background**

```yaml
animated_background: your_config
```

**Version Numbers**

  - Home Assistant: 0.113.3
  - Animated Background: v0.6.3

**Browser console log**
I cannot see that on my tablet or phone.

**To Reproduce**
see video

**Expected behavior**
Not this issue.

**Device (please complete the following information):**
See above

**Screenshots**
See attached video
