### ISSUE TITLE
custom sensor problem - only showing default url

### ISSUE THREAD

**Issue by 0lmagalhaes0** [Villhellm/lovelace-animated-background#36]
After creation of a custom sensor to sum sun and weather, only the standard background is being showed.

Configuration.yaml (copied from example in documentation, I didn't build any template manually)
```
sensor:
  - platform: template
    sensors:
      sun_weather:
        friendly_name: "Sun and Weather"
        value_template: "{{states('sun.sun') + '-' + states('home.weather')}}"
```

**Your view configuration if it contains animated_background**

raw config
```
animated_background:
  default_url: 'https://cdn.flixel.com/flixel/ypy8bw9fgw1zv2b4htp2.hd.mp4'     #that's the only one showing up
  entity: sensor.sun_weather
  state_url:
    above_horizon-sunny:
      - 'https://1drv.ms/v/s!AlUhvEdB-IMWxC7vu17T6mqTsHiF'
    above_horizon-partlycloudy:
      - 'https://1drv.ms/v/s!AlUhvEdB-IMWxCXubRfvvYmCP_mX'
    above_horizon-cloudy:
      - 'https://1drv.ms/v/s!AlUhvEdB-IMWxC8b3r8ZOLDBkwTU'
```
There are other sensor values, but I also tried with only these and the original urls and got the same problem (only default url showing up)

**Version Numbers**
  - Home Assistant: 0.116.4
  - Animated Background: v0.6.3

**Browser console log**
Uncaught TypeError: Cannot read property 'background' of null
    at removeDefaultBackground (animated-background.js:535)
    at animated-background.js:576
animated-background.js:28 Animated Background: Starting
chunk.dbba5c652adfa0940143.js:26537 Detected removal of the top Blocking Element.
Uncaught (in promise)
Animated Background: Starting
Failed to load resource: the server responded with a status of 404 (Not Found)

**To Reproduce**
I created the new sensor in configuration.yaml, changed from standard weather to new sensor (sun and weather) in raw editor, added new weather status as per its documentation (like snowy-rain and windy, for example) and new video sources. Restarted HA. Now it's cloudy and sun above horizon. I tried replacing the new video for the standard one (previously working), with no difference. The new custom sensor is being recognized by the system. Re-replaced the videos by the original ones. Re-restarted HA. No difference.

**Expected behavior**
I expected to add custom videos (hosted in One Drive, Dropbox or other) to mirror weather and sun condition (night videos for night time and day videos for day time, according to their respective weather conditions).

**Device (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 86.0.4240.111 (Official Build) (64-bit)

**Screenshots**
It seems something is wrong in my sensor configuration, but since the codes are here, I wouldn't know what screenshot would be further helpful.

Sorry to bother, I'm a beginner with these technical configurations, so I'm pretty sure it's my fault.
