### ISSUE TITLE
display_user_agent: true does not do anything

### ISSUE THREAD

**Issue by mihail4anov** [Villhellm/lovelace-animated-background#40]
**Describe the bug**
display_user_agent: true does not show any message in chrome or Microsoft Edge browser. I did a reboot, but still nothing.

**Your Animated Background configuration**

```yaml
animated_background:
  default_url: 'https://cdn.flixel.com/flixel/ypy8bw9fgw1zv2b4htp2.hd.mp4'
  display_user_agent: true
  entity: weather.openweathermap
  state_url:
    sunny:
      - 'https://cdn.flixel.com/flixel/hlhff0h8md4ev0kju5be.hd.mp4'
      - 'https://cdn.flixel.com/flixel/zjqsoc6ecqhntpl5vacs.hd.mp4'
      - 'https://cdn.flixel.com/flixel/jvw1avupguhfbo11betq.hd.mp4'
      - 'https://cdn.flixel.com/flixel/8cmeusxf3pkanai43djs.hd.mp4'
      - 'https://cdn.flixel.com/flixel/guwb10mfddctfvwioaex.hd.mp4'
    partlycloudy:
      - 'https://cdn.flixel.com/flixel/13e0s6coh6ayapvdyqnv.hd.mp4'
      - 'https://cdn.flixel.com/flixel/aorl3skmssy7udwopk22.hd.mp4'
      - 'https://cdn.flixel.com/flixel/qed6wvf2igukiioykg3r.hd.mp4'
      - 'https://cdn.flixel.com/flixel/3rd72eezaj6d23ahlo7y.hd.mp4'
      - 'https://cdn.flixel.com/flixel/9m11gd43m6qn3y93ntzp.hd.mp4'
      - 'https://cdn.flixel.com/flixel/hrkw2m8eofib9sk7t1v2.hd.mp4'
    cloudy:
      - 'https://cdn.flixel.com/flixel/13e0s6coh6ayapvdyqnv.hd.mp4'
      - 'https://cdn.flixel.com/flixel/aorl3skmssy7udwopk22.hd.mp4'
      - 'https://cdn.flixel.com/flixel/qed6wvf2igukiioykg3r.hd.mp4'
      - 'https://cdn.flixel.com/flixel/3rd72eezaj6d23ahlo7y.hd.mp4'
      - 'https://cdn.flixel.com/flixel/9m11gd43m6qn3y93ntzp.hd.mp4'
      - 'https://cdn.flixel.com/flixel/hrkw2m8eofib9sk7t1v2.hd.mp4'
    mostlycloudy:
      - 'https://cdn.flixel.com/flixel/e95h5cqyvhnrk4ytqt4q.hd.mp4'
      - 'https://cdn.flixel.com/flixel/l2bjw34wnusyf5q2qq3p.hd.mp4'
      - 'https://cdn.flixel.com/flixel/rrgta099ulami3zb9fd2.hd.mp4'
    clear-night:
      - 'https://cdn.flixel.com/flixel/x9dr8caygivq5secll7i.hd.mp4'
      - 'https://cdn.flixel.com/flixel/v26zyfd6yf0r33s46vpe.hd.mp4'
      - 'https://cdn.flixel.com/flixel/ypy8bw9fgw1zv2b4htp2.hd.mp4'
      - 'https://cdn.flixel.com/flixel/rosz2gi676xhkiw1ut6i.hd.mp4'
    fog:
      - 'https://cdn.flixel.com/flixel/vwqzlk4turo2449be9uf.hd.mp4'
      - 'https://cdn.flixel.com/flixel/5363uhabodwwrzgnq6vx.hd.mp4'
    rainy: 'https://cdn.flixel.com/flixel/f0w23bd0enxur5ff0bxz.hd.mp4'
title: Мой дом
views:
  - badges: []
    cards:
  ...
```

**Version Numbers**

  - Home Assistant: 2021.1.0
  - Animated Background: v0.6.3

**Expected behavior**
I want to exlude HA mobile app from animated background.

**Device (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 87.0.4280.88
