### ISSUE TITLE
Switching by days of the week + sunrise or sunset

### ISSUE THREAD

**Issue by DivanX10** [Villhellm/lovelace-animated-background#47]
I can configure switching video wallpapers by days of the week or sunrise or sunset. Tell me how to make it so that you can switch not only by days of the week but also by sunrise or sunset? The first example works on days of the week, and the second example does not work on days of the week + sunrise or sunset.

This option works on days of the week
```
animated_background:
  default_url: /local/animated-background/day/01.mp4
  included_users:
    - users_01
  entity: sensor.dayoftheweek
  state_url:
    Thursday:
      - /local/animated-background/day/Switzerland_01.mp4
      - /local/animated-background/night/04.mp4
      - /local/animated-background/night_space/Space_05.mp4
    Friday:
      - /local/animated-background/day/Switzerland_01.mp4
      - /local/animated-background/night/04.mp4
```

This option does not work on days of the week + sunrise or sunset
```
animated_background:
  default_url: /local/animated-background/day/01.mp4
  included_users:
    - users_01
  entity: sensor.dayoftheweek
  state_url:
    Thursday:
      above_horizon:
        - /local/animated-background/day/Switzerland_01.mp4
        - /local/animated-background/night/04.mp4
      below_horizon:
        - /local/animated-background/night_space/Space_05.mp4
    Friday:
      above_horizon:
        - /local/animated-background/day/Switzerland_01.mp4
        - /local/animated-background/night/04.mp4
      below_horizon:
        - /local/animated-background/night_space/Space_05.mp4
```
