### ISSUE TITLE
[Feature Request] Allow configuring opacity of the background

### ISSUE THREAD

**Issue by illuzn** [Villhellm/lovelace-animated-background#49]
This is a feature request to adjust the opacity of the background. This is useful for dark themed backgrounds so that bright colours in the mp4 can be muted using opacity.

I've manually done this by editing line 488 of the js and adding in my desired opacity but it would be good if this could be done using the lovelace yaml configuration.

**Comment by chrisborell** [comment]
Could you please share the code you used?

**Comment by illuzn** [comment]
Sure, pretty simple.

In animated-background.js, change the following code block
```css
      .bg-video{
          min-width: 100vw; 
          min-height: 100vh;
          opacity: XX%
      }
```
Where XX is a number from 0-100% corresponding to the opacity level.

Edit: This appears at line 485.
