### ISSUE TITLE
No more working with HA 0.108.x

### ISSUE THREAD

**Issue by SeByDocKy** [Villhellm/lovelace-animated-background#6]
No more animation.....  :(

**Comment by Villhellm** [comment]
Update should fix it as long as whatever theme you are using sets `primary-background-color` to `transparent`. They changed the way that themes function, so access to the element style is more difficult to change. I might fix it in the future, but I'm done working on this for now.

**Comment by Villhellm** [comment]
Okay the latest commit should fix the problem with no workaround necessary. Please let me know if you have any more issues

**Comment by SeByDocKy** [comment]
> Okay the latest commit should fix the problem with no workaround necessary. Please let me know if you have any more issues


Just tested .... but for me got a white background with .... :( no animation ... :(

**Comment by Villhellm** [comment]
Do you see any errors in the browser console? And are you positive you've cleared your browser cache?

**Comment by SeByDocKy** [comment]
Cache cleared ....

got that 
```
Failed to load resource: the server responded with a status of 404 (Not Found)
/local/custom_ui/custom-weather-animated.html:1 Failed to load resource: the server responded with a status of 404 (Not Found)
/local/custom_ui/custom-weather-card.html:1 Failed to load resource: the server responded with a status of 404 (Not Found)
/local/custom_ui/custom-weather-animated.html:1 Failed to load resource: the server responded with a status of 404 (Not Found)
fold-entity-row.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
atomic_calendar.js:1 atomic_calendar v0.8.9 loaded
animated-background.js:23 animated background starting
load_resource.ts:17 Uncaught (in promise) https://xxxxxxx.org/hacsfiles/lovelace-fold-entity-row/fold-entity-row.js
memory-free:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)
hooks.js:605 Loaded CustomUI 20190518
atomic_calendar.js:1 atomic_calendar v0.8.9 loaded
memory-free:1 GET https://xxxxxxx.org/api/hassio_ingress/ZAh--QoL9VZF6FYBpsDjFsKGWGsh1dtTkX1xEK19InA/d/0z9WltrZz/memory-free?orgId=1&refresh=5s 401 (Unauthorized)```

**Comment by souravj96** [comment]
Same issue here!
I'm using Home Assistant 0.108.3
oxfordblue theme
and `setted primary-background-color: transparent`
in browser console, it's printing `Animated Background starting`
but also not getting the background.

**Comment by Villhellm** [comment]
Are you on the latest version? There should be more information in the console than that.

**Comment by souravj96** [comment]
yes i'm at the latest version. and nothing else at my web console

**Comment by Villhellm** [comment]
Can you post your animated_background configuration and what browser are you using?

**Comment by souravj96** [comment]
i'm using chrome. and the configuration file is automatically installed using hacs

**Comment by Villhellm** [comment]
No, the configuration is manually added. Did you read the instructions for setup?

**Comment by souravj96** [comment]
yeah read that thing, but i was unable to attach it with my hassio because i   couldn't find the `ui-lovelace.yaml` file

**Comment by Villhellm** [comment]
Then you need to go into your lovelace raw configuration (top right three dots > Configure UI > Raw configuration editor) and add it there.

**Comment by souravj96** [comment]
got it! let me do this.

**Comment by souravj96** [comment]
now it gives me this logs on console
```
Animated Background starting
Animated Background is not enabled in Lovelace configuration
```

and here is my configuration
```
animated_background:
  default_url: /community/lovelace-animated-background/background-animations/sunny.html
  entity: weather.home
  included_users:
    - 01db6dd8f30a4650a0f8ea2e35905e11
  state_url:
    clear-night: /community/lovelace-animated-background/background-animations/night.html
    cloudy: /community/lovelace-animated-background/background-animations/cloudy.html
    fog: /community/lovelace-animated-background/background-animations/fog.html
    mostlycloudy: >-
      /community/lovelace-animated-background/background-animations/mostlycloudy.html
    partlycloudy: /community/lovelace-animated-background/background-animations/cloudy.html
    sunny: /community/lovelace-animated-background/background-animations/sunny.html
custom_header:
  editor_warnings: false
resources:
  - type: module
    url: /community/lovelace-animated-background/animated-background.js
title: Home
views:
```
